### ISSUE TITLE
Rundeck cookbook does not depend on yum cookbook. Errors occur in test kitchen

### ISSUE THREAD

**Issue by isuftin** [sous-chefs/rundeck#75]
This is being run in Test Kitchen against a CentOS 6.7 guest.

```
-----> Starting Kitchen (v1.4.2)
-----> Converging <server-centos-67-vbox>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <server-centos-67-vbox>
       Starting Chef Client, version 12.7.2
       resolving cookbooks for run list: ["rundeck::server"]
       Synchronizing Cookbooks:
         - sudo (2.9.0)
         - java (1.39.0)
         - packagecloud (0.1.1)
         - runit (1.7.6)
         - apache2 (3.1.0)
         - apt (2.9.2)
         - rundeck (2.0.12)
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/rundeck/recipes/server.rb
       ================================================================================

       NoMethodError
       -------------
       No resource or method named `yum_repository' for `Chef::Recipe "server_install"'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/rundeck/recipes/server_install.rb:33:in `from_file'
         /tmp/kitchen/cache/cookbooks/rundeck/recipes/server.rb:21:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/rundeck/recipes/server_install.rb:

        26:    rundeck_secret = Chef::EncryptedDataBagItem.load_secret(node['rundeck']['secret_file'])
        27:    rundeck_secure = Chef::EncryptedDataBagItem.load(node['rundeck']['rundeck_databag'], node['rundeck']['rundeck_databag_secure'], rundeck_secret)
        28:    rundeck_users = Chef::EncryptedDataBagItem.load(node['rundeck']['rundeck_databag'], node['rundeck']['rundeck_databag_users'], rundeck_secret)
        29:  end
        30:  
        31:  case node['platform_family']
        32:  when 'rhel'
        33>>   yum_repository 'rundeck' do
        34:      description 'Rundeck - Release'
        35:      url 'http://dl.bintray.com/rundeck/rundeck-rpm'
        36:      gpgcheck false
        37:      action :add
        38:    end
        39:  
        40:    package 'rundeck' do
        41:      version node['rundeck']['rpm']['version']
        42:      action :install


       Running handlers:
       [2016-02-16T20:55:16+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-16T20:55:16+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2016-02-16T20:55:16+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-16T20:55:16+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-16T20:55:16+00:00] ERROR: No resource or method named `yum_repository' for `Chef::Recipe "server_install"'
       [2016-02-16T20:55:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by isuftin** [comment]
https://github.com/Webtrends/rundeck/pull/76
