### ISSUE TITLE
chef-rundeck fails on Ubuntu

### ISSUE THREAD

**Issue by gmr** [sous-chefs/rundeck#78]
Because of something weird with how the job is setup with runit, it errors when building the XML response.

When i run the command manually with it disabled in runit, it works ok.

```
[2016-03-16T18:09:56+00:00] ERROR: === could not generate xml for {"name"=>"foo.bar", "chef_environment"=>"production", "run_list"=>role[base], "recipes"=>[], "roles"=>["base"], "fqdn"=>"foo.bar", "hostname"=>"foo.bar", "kernel_machine"=>"x86_64", "kernel_os"=>"GNU/Linux", "platform"=>"ubuntu", "platform_version"=>"14.04", "tags"=>["statsd"]}:  undefined method `unpack' for nil:NilClass
[2016-03-16T18:09:56+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/xml_escape.rb:109:in `rescue in xml_escape'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/xml_escape.rb:106:in `xml_escape'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:188:in `build_node'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:152:in `block in build_project'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:140:in `each'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:140:in `build_project'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:82:in `block in configure'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
[2016-03-16T18:09:56+00:00] INFO: nodes complete (project: 'default', total: 396, failed: 0)
[2016-03-16T18:09:56+00:00] DEBUG: #<File:/tmp/chef-rundeck-default.xml>
```

**Comment by gmr** [comment]
Changing ``/etc/sv/chef-rundeck/run`` to use ``su`` instead of ``chpst`` works:

```
#!/bin/sh
exec 2>&1
exec 1> /var/log/chef-rundeck/server.log
exec \
su - rundeck  -c "/opt/chef/embedded/bin/chef-rundeck -c /etc/chef/rundeck.rb -f /etc/chef/chef-rundeck.json -w https://chef.svc.prd.csh -o 0.0.0.0 -p 9980 -t 360
```

**Comment by gmr** [comment]
Solution for me was to use the upstart switch -- feel free to close, but figured you'd want to be aware of the issue.

**Comment by pcross616** [comment]
I will look in to this, we run on ubuntu and don't have to do anything special.

What version of Ubuntu are you running?

**Comment by gmr** [comment]
That was on Trusty. I also had an issue with the upstart config not having the same start switches as the runit version. I've been planning on pulling together a PR on this soon -- just need the spare cycles to do so.

**Comment by jwilf** [comment]
Same problem for me on CentOS 6. Forcing use of upstart instead of runit fixed it.
